project:
  type: website

website:
  title: "<span class='site-name'><strong>Your</strong> Name</span>"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: Résumé for Research
        href: resume.qmd
      - text: Outputs
        href: outputs.qmd
    right:
      - icon: github
        href: https://github.com/YOURUSERNAME
      - icon: envelope
        href: mailto:YOUR.EMAIL@domain


format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    smooth-scroll: true
