project:
  type: website

website:
  title: "Portfolio Template"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: Résumé for Research
        href: resume.qmd
      - text: Outputs
        href: outputs.qmd

format:
  html:
    theme: cosmo
    toc: true
