project:
  type: website
  resources:
    - assets/**
  execute-dir: project

website:
  title: "<span class='site-name'><strong>Your</strong> Name</span>"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: pages/projects.qmd
      - text: Outputs
        href: pages/outputs.qmd
      - text: Résumé for Research
        href: pages/resume.qmd
      - text: CV
        href: pages/cv.qmd

    right:
      - icon: github
        href: https://github.com/YOURUSERNAME
      - icon: envelope
        href: mailto:YOUR.EMAIL@domain


format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    smooth-scroll: true
